# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wbh-A9rz8JbXk1m-wwizwKp8fShLs12O
"""

import pandas as pd

import pandas as pd
pd.read_csv

df = pd.read_csv('/content/human_cognitive_performance.csv')

filtered_df = df[['Caffeine_Intake','Reaction_Time','Cognitive_Score', 'Age','Gender']].copy()
filtered_df.dropna(inplace=True)

import pandas as pd
import numpy as np
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv(('/content/human_cognitive_performance.csv'))
#filter columns
filtered_df =df[['Caffeine_Intake','Reaction_Time','Cognitive_Score','Age','Gender']].copy()
filtered_df.dropna(inplace=True)

#Distibution analysis
dist_stats = filtered_df.describe()

#Cognitive score comparison (caffeine_intake)
cog_caf= filtered_df.groupby('Caffeine_Intake')['Cognitive_Score'].agg(['mean','std','count'])

#Reaction time comparison (Caffeine_intake)
rt_caf= filtered_df.groupby('Caffeine_Intake')['Reaction_Time'].agg(['mean','std','count'])

# outputs
print("Filtered Dataset Shape:", filtered_df.shape)
print("\nDistribution Statistics:\n", dist_stats)
print("\nCognitive Score by Caffeine Intake:\n", cog_caf)
print("\nReaction Time by Caffeine Intake:\n", rt_caf)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#Load and filter previous data
filtered_df =df[['Caffeine_Intake','Reaction_Time','Cognitive_Score','Age','Gender']].copy()
filtered_df.dropna(inplace=True)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load and filter data
df = pd.read_csv('human_cognitive_performance.csv')
filtered_df = df[['Caffeine_Intake', 'Reaction_Time', 'Cognitive_Score']].copy()
filtered_df.dropna(inplace=True)

# Set style
plt.style.use('default')
sns.set_palette("husl")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# 1. Caffeine Intake vs Reaction Time
ax1.scatter(filtered_df['Caffeine_Intake'], filtered_df['Reaction_Time'],
           alpha=0.6, s=10, color='steelblue')
sns.regplot(x='Caffeine_Intake', y='Reaction_Time', data=filtered_df,
            scatter=False, ax=ax1, color='red', line_kws={'linewidth': 2})
ax1.set_title('Caffeine Intake vs Reaction Time', fontsize=14, fontweight='bold')
ax1.set_xlabel('Caffeine Intake (mg)')
ax1.set_ylabel('Reaction Time (ms)')
ax1.grid(True, alpha=0.3)

# 2. Caffeine Intake vs Cognitive Score
ax2.scatter(filtered_df['Caffeine_Intake'], filtered_df['Cognitive_Score'],
           alpha=0.6, s=10, color='darkorange')
sns.regplot(x='Caffeine_Intake', y='Cognitive_Score', data=filtered_df,
            scatter=False, ax=ax2, color='green', line_kws={'linewidth': 2})
ax2.set_title('Caffeine Intake vs Cognitive Score', fontsize=14, fontweight='bold')
ax2.set_xlabel('Caffeine Intake (mg)')
ax2.set_ylabel('Cognitive Score')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()


# Print correlation values for reference
corr_rt = filtered_df['Caffeine_Intake'].corr(filtered_df['Reaction_Time'])
corr_cog = filtered_df['Caffeine_Intake'].corr(filtered_df['Cognitive_Score'])
print(f"Caffeine vs Reaction Time correlation: {corr_rt:.3f}")
print(f"Caffeine vs Cognitive Score correlation: {corr_cog:.3f}")

#Create bins and compute averages
filtered_df['Caffeine_Bin'] = pd.cut(filtered_df['Caffeine_Intake'], bins=10)
summary = filtered_df.groupby('Caffeine_Bin').agg({'Reaction_Time': ['mean','std'], 'Cognitive_Score': ['mean','std']}).round(2)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

#Caffeine vs reaction time (binned means)
bins_rt = summary['Reaction_Time']['mean']
ax1.errorbar(range(len(bins_rt)), bins_rt, yerr=summary['Reaction_Time']['std'],fmt='o-',capsize=5)
ax1.set_title('Caffeine Intake vs Reaction Time (Binned Averages \u00b11 SD)')
ax1.set_xlabel('Caffeine Intake Bin')
ax1.set_ylabel('Mean Reaction Time (ms)')
ax1.set_xticks(range(10))
ax1.set_xticklabels([f'{i*50}-{i*50+49}' for i in range(10)], rotation=45)

# Caffeine vs Cognitive Score (binned means)
bins_cog = summary['Cognitive_Score']['mean']
ax2.errorbar(range(len(bins_cog)), bins_cog,
             yerr=summary['Cognitive_Score']['std'], fmt='o-', capsize=5, color='orange')
ax2.set_title('Caffeine vs Cognitive Score (Binned Averages \u00b11 SD)')
ax2.set_xlabel('Caffeine Intake Bins')
ax2.set_ylabel('Mean Cognitive Score')
ax2.set_xticks(range(10))
ax2.set_xticklabels([f'{i*50}-{i*50+49}' for i in range(10)], rotation=45)

plt.tight_layout()
plt.show()
print(summary)

# 1. hexbin plots density+ summary
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('human_cognitive_performance.csv')
filtered_df = df[['Caffeine_Intake', 'Reaction_Time', 'Cognitive_Score']].copy()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Hexbin: Caffeine vs Reaction Time
hb1 = ax1.hexbin(filtered_df['Caffeine_Intake'], filtered_df['Reaction_Time'],
                 gridsize=30, cmap='Blues', mincnt=1)
ax1.set_title('Caffeine vs Reaction Time (Hexbin)')
ax1.set_xlabel('Caffeine Intake (mg)')
ax1.set_ylabel('Reaction Time (ms)')
plt.colorbar(hb1, ax=ax1, label='Count')

# Hexbin: Caffeine vs Cognitive Score
hb2 = ax2.hexbin(filtered_df['Caffeine_Intake'], filtered_df['Cognitive_Score'],
                 gridsize=30, cmap='Oranges', mincnt=1)
ax2.set_title('Caffeine vs Cognitive Score (Hexbin)')
ax2.set_xlabel('Caffeine Intake (mg)')
ax2.set_ylabel('Cognitive Score')
plt.colorbar(hb2, ax=ax2, label='Count')

plt.tight_layout()
plt.show()

# Save your filtered dataset
filtered_df.to_csv('clean_cognitive_data.csv', index=False)

# Download immediately
from google.colab import files
files.download('clean_cognitive_data.csv')

cog_caf.to_csv('cognitive_caf.csv', index=False)

from google.colab import files
files.download('cognitive_caf.csv')

dist_stats.to_csv('data_summary.csv', index=False)

from google.colab import files
files.download('data_summary.csv')

